# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  # Hold ourselves to a high bar
  range: 80..90
  round: down
  precision: 1
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        # Avoid false negatives
        threshold: 1%
    patch:
      default:
        informational: true

ignore:
  - "src/bin" # don't consider binaries in coverage report
  - "tests" # we also don't care about coverage of test code
  - "benches" # or coverage of benchmarks

# Make comments less noisy
comment:
  layout: "files"
  require_changes: true
